  <!-- copy -->
  <footer class="bg-dark">

    <div class="container py-5 ">
      <div class="row">
        <div class="col-md-4 d-none d-md-block">
          <img src="assets/img/logo-bg-none.svg" alt="armandotuweb">
        </div>

       <div class="col-12 col-md-8 mb-4 d-flex align-items-center justify-content-center">
          <p class="text-left text-white">
            <i class="fas fa-mobile-alt"></i> +51 958 478 073 <br>
            <i class="fas fa-envelope"></i> armandoaepp@gmail.com
          </p>
        </div>

      </div>
    </div>



    <div class="copy bg-white-25">
      <div class="container py-3">
        <div class="row">
          <div class="col-12 text-center fw-300 opacity-2">
            ARMANDOTUWEB &COPY; 2019 - Todos los derechos reservados
          </div>
        </div>
      </div>
    </div>
  </footer>