<meta charset="utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<?php
// extraemos todas la variables
extract($setvar);

$titulo      = !empty($titulo ) ? $titulo : "Admin | Armandotuweb" ;
$follow      = !empty($follow ) ? $follow : "index, follow" ;
$description = !empty($description ) ? $description : "Admin templa bootstrap 4" ;
$keywords    = !empty($keywords ) ? $keywords : "admin template, admin bootstrap 4" ;

$path  = !empty($path) ? $path  : '';

$style = '' ;
if (!empty($theme) && $theme != 'default')
{
  $style = $theme.'/app';
}
else
{
  $style = 'app';
}

// $style = !empty($style) || $style == 'default'  ? $style.'/app' : 'app';

?>

<title><?php echo $titulo; ?></title>
<link rel="icon" href="<?php echo $path;?>assets/images/favicon.png" sizes="32x32" />
<meta name="robots" content="<?php echo $follow; ?>" />

<meta name="description" content="<?php echo $description; ?>" />
<meta name="keywords" content="<?php echo $keywords; ?>" />
<meta name="robots" content="<?php echo $setvar['follow']; ?>" />

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">

<link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,400i,,700,700i,900" rel="stylesheet">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="css/styles.examples.css">
<link rel="stylesheet" href="../css/helper-css.css">
