<?php
$sidebar = !empty($sidebar) ? $sidebar : [] ;
extract($sidebar);

$sidebar_class  = !empty($sidebar_class ) ? $sidebar_class : "" ;
$sidebar_toggle = !empty($sidebar_toggle ) ? $sidebar_toggle : "all" ;
$sidebar_active = !empty($sidebar_active ) ? $sidebar_active : [0,0] ;

?>
<nav class="sidebar <?php echo $sidebar_class; ?> scroll-item" data-sidebar="menu" data-menu-toggle="<?php echo $sidebar_toggle; ?>">
  <div class="sidebar-header">
    <span class="d-block"> Intranet </span>
  </div>
  <span class="heading">Components</span>
  <ul class="sidenav">
    <li>
      <a class="menu <?php if($sidebar_active[0] == 4){echo 'active';} ?>" href="#" role="button">
        <i class="fas fa-tachometer-alt"></i> Dashboard
      </a>
      <ul class="menu-items">
        <li>
          <a class="<?php if($sidebar_active[0] == 4 && $sidebar_active[1] == 1){echo 'active';} ?>" href="<?php echo $path_sidebar ?>dashboard/dashboard.php">
            <i class="icofont icofont-curved-right"></i> Dashboard
          </a>
        </li>
      </ul>
    </li>

    <li>
      <a class="menu <?php if($sidebar_active[0] == 1){echo 'active';} ?>" href="#" role="button">
        <i class="fab fa-elementor"></i> UI Elements
      </a>
      <ul class="menu-items">
        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 1){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/buttons.php">
            <i class="icofont icofont-curved-right"></i> Buttons
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 2){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/bagdes.php">
            <i class="icofont icofont-curved-right"></i> Bagdes
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 3){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/typography.php">
            <i class="icofont icofont-curved-right"></i> Typography
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 4){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/alerts.php">
            <i class="icofont icofont-curved-right"></i> Alerts
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 5){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/cards.php">
            <i class="icofont icofont-curved-right"></i> Cards
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 6){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/collapse.php">
            <i class="icofont icofont-curved-right"></i> Collapse
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 7){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/accordion.php">
            <i class="icofont icofont-curved-right"></i> Accordions
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 8){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/list-group.php">
            <i class="icofont icofont-curved-right"></i> List Group
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 9){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/media-object.php">
            <i class="icofont icofont-curved-right"></i> Media Object
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 10){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/pagination.php">
            <i class="icofont icofont-curved-right"></i> Pagination
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 1 && $sidebar_active[1] == 11){echo 'active';} ?>" href="<?php echo $path_sidebar ?>ui-elements/progress.php">
            <i class="icofont icofont-curved-right"></i> Progress
          </a>
        </li>


      </ul>
    </li>

    <li>
      <a class="menu <?php if($sidebar_active[0] == 2){echo 'active';} ?>" href="#" role="button">
        <i class="fas fa-location-arrow"></i> Navigation
      </a>
      <ul class="menu-items">
        <li>
          <a class="<?php if($sidebar_active[0] == 2 && $sidebar_active[1] == 1){echo 'active';} ?>" href="<?php echo $path_sidebar ?>navigation/navbars.php">
            <i class="icofont icofont-curved-right"></i> Navbars
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 2 && $sidebar_active[1] == 2){echo 'active';} ?>" href="<?php echo $path_sidebar ?>navigation/navbars-variants.php">
            <i class="icofont icofont-curved-right"></i> Navbars Variants
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 2 && $sidebar_active[1] == 5){echo 'active';} ?>" href="<?php echo $path_sidebar ?>navigation/breadcrumb.php">
            <i class="icofont icofont-curved-right"></i> Breadcrumb
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 2 && $sidebar_active[1] == 3){echo 'active';} ?>" href="<?php echo $path_sidebar ?>navigation/sidebar.php">
            <i class="icofont icofont-curved-right"></i> Sidebar </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 2 && $sidebar_active[1] == 4){echo 'active';} ?>" href="<?php echo $path_sidebar ?>navigation/sidebar-menu-all.php">
            <i class="icofont icofont-curved-right"></i> Sidebar Menu All
          </a>
        </li>

      </ul>
    </li>

    <li>
      <a class="menu <?php if($sidebar_active[0] == 3){echo 'active';} ?>" href="#" role="button">
        <i class="fas fa-image"></i> Content
      </a>
      <ul class="menu-items">
        <li>
          <a class="<?php if($sidebar_active[0] == 3 && $sidebar_active[1] == 1){echo 'active';} ?>" href="<?php echo $path_sidebar ?>content/images.php">
            <i class="icofont icofont-curved-right"></i> Images
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 3 && $sidebar_active[1] == 2){echo 'active';} ?>" href="<?php echo $path_sidebar ?>content/tables.php">
            <i class="icofont icofont-curved-right"></i> Tables
          </a>
        </li>

      </ul>
    </li>

    <li>
      <a class="menu <?php if($sidebar_active[0] == 5){echo 'active';} ?>" href="#" role="button">
        <i class="fas fa-swatchbook"></i> Utilities
      </a>
      <ul class="menu-items">
        <li>
          <a class="<?php if($sidebar_active[0] == 5 && $sidebar_active[1] == 1){echo 'active';} ?>" href="<?php echo $path_sidebar ?>utilities/colors.php">
            <i class="icofont icofont-curved-right"></i> Colors
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 5 && $sidebar_active[1] == 2){echo 'active';} ?>" href="<?php echo $path_sidebar ?>utilities/borders.php">
            <i class="icofont icofont-curved-right"></i> Borders
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 5 && $sidebar_active[1] == 3){echo 'active';} ?>" href="<?php echo $path_sidebar ?>utilities/radius.php">
            <i class="icofont icofont-curved-right"></i> Radius
          </a>
        </li>
      </ul>
    </li>

    <li>
      <a class="menu <?php if($sidebar_active[0] == 8){echo 'active';} ?>" href="#" role="button">
        <i class="fas fa-pen-nib"></i> Theme Variants
      </a>
      <ul class="menu-items">

        <li>
          <a class="<?php if($sidebar_active[0] == 8 && $sidebar_active[1] == 1){echo 'active';} ?>" href="<?php echo $path_sidebar ?>theme-variants/theme-dark.php">
            <i class="icofont icofont-curved-right"></i> Theme Dark
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 8 && $sidebar_active[1] == 2){echo 'active';} ?>" href="<?php echo $path_sidebar ?>theme-variants/sidebar-default.php">
            <i class="icofont icofont-curved-right"></i> Sidebar Default
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 8 && $sidebar_active[1] == 3){echo 'active';} ?>" href="<?php echo $path_sidebar ?>theme-variants/sidebar-primary.php">
            <i class="icofont icofont-curved-right"></i> Sidebar Primary
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 8 && $sidebar_active[1] == 4){echo 'active';} ?>" href="<?php echo $path_sidebar ?>theme-variants/sidebar-inverse.php">
            <i class="icofont icofont-curved-right"></i> Sidebar Inverse
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 8 && $sidebar_active[1] == 5){echo 'active';} ?>" href="<?php echo $path_sidebar ?>theme-variants/sidebar-dark.php">
            <i class="icofont icofont-curved-right"></i> Sidebar Dark
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 8 && $sidebar_active[1] == 6){echo 'active';} ?>" href="<?php echo $path_sidebar ?>theme-variants/theme-dark-table.php">
            <i class="icofont icofont-curved-right"></i> Theme Dark Table
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 8 && $sidebar_active[1] == 7){echo 'active';} ?>" href="<?php echo $path_sidebar ?>theme-variants/brand-sidebar-primary.php">
            <i class="icofont icofont-curved-right"></i> Brandh Sidebar Primary
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 8 && $sidebar_active[1] == 8){echo 'active';} ?>" href="<?php echo $path_sidebar ?>theme-variants/brand-sidebar-dark.php">
            <i class="icofont icofont-curved-right"></i> Brandh Sidebar Dark
          </a>
        </li>

      </ul>
    </li>

    <li>
      <a class="menu <?php if($sidebar_active[0] == 6){echo 'active';} ?>" href="#" role="button">
        <i class="fas fa-sign-in-alt"></i> Pages
      </a>
      <ul class="menu-items">
        <li>
          <a class="<?php if($sidebar_active[0] == 6 && $sidebar_active[1] == 1){echo 'active';} ?>" target="_blank"
            href="<?php echo $path_sidebar ?>pages/login.php">
            <i class="icofont icofont-curved-right"></i> Login
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 6 && $sidebar_active[1] == 2){echo 'active';} ?>" target="_blank"
            href="<?php echo $path_sidebar ?>pages/login-2.php">
            <i class="icofont icofont-curved-right"></i> Login 2
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 6 && $sidebar_active[1] == 3){echo 'active';} ?>" target="_blank"
            href="<?php echo $path_sidebar ?>pages/login-3.php">
            <i class="icofont icofont-curved-right"></i> Login 3
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 6 && $sidebar_active[1] == 4){echo 'active';} ?>" target="_blank"
            href="<?php echo $path_sidebar ?>pages/login-4.php">
            <i class="icofont icofont-curved-right"></i> Login 4
          </a>
        </li>
        <li>
          <a class="<?php if($sidebar_active[0] == 6 && $sidebar_active[1] == 5){echo 'active';} ?>" target="_blank"
            href="<?php echo $path_sidebar ?>pages/login-5.php">
            <i class="icofont icofont-curved-right"></i> Login 5
          </a>
        </li>

      </ul>
    </li>

    <li>
      <a class="menu <?php if($sidebar_active[0] == 7){echo 'active';} ?>" href="#" role="button">
        <i class="fas fa-address-card"></i> Admin
      </a>
      <ul class="menu-items">
        <li>
          <a class="<?php if($sidebar_active[0] == 7 && $sidebar_active[1] == 1){echo 'active';} ?>"
            href="<?php echo $path_sidebar ?>admin/personas.php">
            <i class="icofont icofont-curved-right"></i> Personas
          </a>
        </li>

        <li>
          <a class="<?php if($sidebar_active[0] == 7 && $sidebar_active[1] == 2){echo 'active';} ?>"
            href="<?php echo $path_sidebar ?>admin/list-demo2.php">
            <i class="icofont icofont-curved-right"></i> List demo 2
          </a>
        </li>

      </ul>
    </li>



  </ul>
</nav>